Dense Layers

In [12]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = 3
dense = Dense(units=n_neurons, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()

print('======== Input / weight / bias ==========')
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y_tf.shape)

print(W)

======== Input / weight / bias ==========
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)
[[-0.58918697 -0.30411518  0.32112694]
 [ 0.41577828  0.09263963 -0.29512566]
 [-0.53215677 -0.32095605 -0.48871547]
 [-0.43625855 -0.17577285  0.27676922]
 [-0.4471608   0.22956443  0.49256277]
 [-0.55962294  0.23879433  0.11775053]
 [ 0.34594584 -0.3277993  -0.1530993 ]
 [ 0.40859926 -0.5888572   0.2008391 ]
 [-0.41948473 -0.36120307  0.08009994]
 [-0.04672676  0.26860052 -0.07115835]]


In [17]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = 3
dense = Dense(units=n_neurons, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(tf): \n", Y_tf.numpy())

# calculate with matrix mul
Z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-Z))
print("Y(with mat mul): \n", Y_man_matmul.numpy())

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neurons))

for x_idx in range(N):
    x = X[x_idx]

    for nu_idx in range(n_neurons):
        w, b = W[:, nu_idx], B[nu_idx]

        z = tf.reduce_sum(x * w) + b
        a = 1 / (1 + np.exp(-z))
        Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot product): \n", Y_man_vec)

Y(tf): 
 [[0.7153445  0.308651   0.42706096]
 [0.41625103 0.43936658 0.15866333]
 [0.41991144 0.46275058 0.3710913 ]
 [0.4455725  0.9890655  0.19825467]]
Y(with mat mul): 
 [[0.7153445  0.308651   0.42706096]
 [0.41625106 0.43936658 0.15866332]
 [0.41991144 0.4627506  0.3710913 ]
 [0.4455725  0.9890655  0.19825469]]
Y(with dot product): 
 [[0.7153445  0.30865101 0.42706095]
 [0.41625105 0.43936657 0.15866332]
 [0.41991143 0.46275059 0.37109132]
 [0.44557249 0.98906552 0.19825469]]


In [23]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_features = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X: ", X.shape)
print()

print("W1: ", W1.shape)
print("B1: ", B1.shape)
print("A1: ", A1.shape)
print()

print("W2: ", W2.shape)
print("B2: ", B2.shape)
print("Y: ", Y.shape)

X:  (4, 10)

W1:  (10, 3)
B1:  (3,)
A1:  (4, 3)

W2:  (3, 5)
B2:  (5,)
Y:  (4, 5)


In [25]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_features = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50]

dense_layers = list()

for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)

print('input: ', X.shape)

for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer ", dense_idx)
    print(X.shape)


input:  (4, 10)
After dense layer  0
(4, 10)
After dense layer  1
(4, 20)
After dense layer  2
(4, 30)
After dense layer  3
(4, 40)
After dense layer  4
(4, 50)


In [34]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_features = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)

n_neurons = [3, 4, 5]

dense_layers = list()

for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='sigmoid')
    dense_layers.append(dense)

W, B = list(), list()

for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    
    w, b = dense.get_weights()
    W.append(w)
    B.append(b)
    
print("Y(tensorflow)", X.numpy())


# calculate with matrix mul
for layer_idx in range(len(n_neurons)):
    w, b = W[layer_idx], B[layer_idx]

    X_cp = matmul(X_cp, w) + b
    X_cp = 1 / (1 + exp(-X_cp))
    
print("Y(with mat mul): \n", X_cp.numpy())

# calculate with dot products


Y(tensorflow) [[0.45912108 0.48762915 0.659182   0.69113064 0.41528684]
 [0.46440107 0.51414126 0.6601374  0.6963803  0.4253297 ]
 [0.4595392  0.4770657  0.6540414  0.68146384 0.4196349 ]
 [0.4603545  0.47068137 0.65627116 0.6831931  0.4297684 ]]
Y(with mat mul): 
 [[0.4591211  0.48762915 0.659182   0.6911306  0.41528684]
 [0.46440104 0.5141412  0.6601374  0.69638026 0.4253297 ]
 [0.4595392  0.47706565 0.6540414  0.6814638  0.41963488]
 [0.46035448 0.4706814  0.65627116 0.6831931  0.42976844]]


Model Implementation
- sequential method
- model-subclassing

In [35]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

n_neurons = [3, 4, 5, 6]

# using list
model = list()
for n_neuron in n_neurons:
    model.append(Dense(units=n_neuron, activation='sigmoid'))

# using sequential method
model = Sequential()
for n_neuron in n_neurons:
    model.add(Dense(units=n_neuron, activation='sigmoid'))

In [36]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()

        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=20, activation='sigmoid')

model = TestModel()

Forward Propagation

In [51]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X = tf.random.normal(shape=(4, 10))

n_neurons = [3, 4, 5, 6]

# using sequential method
model = Sequential()
for n_neuron in n_neurons:
    model.add(Dense(units=n_neuron, activation='sigmoid'))

Y = model(X)

# using model-subclassing
class TestModel(Model):
    def __init__(self, n_neurons):
        super(TestModel, self).__init__()
        self.n_neurons = n_neurons

        self.dense_layers = list()
        for n_neuron in self.n_neurons:
            self.dense_layers.append(Dense(units=n_neuron, activation='sigmoid'))

    def call(self, x):
        for dense_layer in self.dense_layers:
            x = dense_layer(x)
        return x

model = TestModel(n_neurons)
Y = model(X)

# using model-subclassing
class TestModel2(Model):
    def __init__(self, n_neurons):
        super(TestModel2, self).__init__()
        self.n_neurons = n_neurons

        self.model = Sequential()
        for n_neuron in self.n_neurons:
            self.model.add(Dense(units=n_neuron, activation='sigmoid'))

    def call(self, x):
        x = self.model(x)
        return x

model = TestModel2(n_neurons)
Y2 = model(X)

Layers in Models

In [53]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.layers))
print(model.layers)

dense1 = model.layers[0]
for tmp in dir(dense1):
    print(tmp)

<class 'list'>
[<keras.layers.core.dense.Dense object at 0x7ff540510400>, <keras.layers.core.dense.Dense object at 0x7ff540514340>]
_TF_MODULE_IGNORED_PROPERTIES
__annotations__
__call__
__class__
__delattr__
__dict__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getstate__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__setstate__
__sizeof__
__str__
__subclasshook__
__weakref__
_activity_regularizer
_add_trackable
_add_trackable_child
_add_variable_with_custom_getter
_auto_config
_auto_get_config
_auto_track_sub_layers
_autocast
_autographed_call
_build_input_shape
_call_spec
_callable_losses
_captured_weight_regularizer
_cast_single_input
_checkpoint_dependencies
_clear_losses
_compute_dtype
_compute_dtype_object
_dedup_weights
_deferred_dependencies
_delete_tracking
_deserialization_dependencies
_deserialize_from_proto
_dtype
_dtype_policy
_dynamic
_eager_losses
_expects_mask_arg
_expect

In [56]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.trainable_variables))
print(len(model.trainable_variables))

for train_var in model.trainable_variables:
    print(train_var.shape)

<class 'list'>
4
(10, 10)
(10,)
(10, 20)
(20,)
