### Conv Layer
Shapes of Conv Layers

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 5
n_filter = 10
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))
conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)


(32, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(32, 26, 26, 10)


Correlation Calculation

In [31]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))
conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
print("y shape: ", y.shape)
print("squeezed y shape: ", y.numpy().squeeze().shape, "\n")

print("Y(tf): ", y.numpy().squeeze(), "\n")

W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)
print(B.shape, "\n")

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1)) # 우선 빈 공간 만들기

for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
        window = images[h:h+k_size, w:w+k_size]
        z = np.sum(window * W) + B
        y_man[h, w] = z

print("Y(man): ", y_man)

y shape:  (1, 3, 3, 1)
squeezed y shape:  (3, 3) 

Y(tf):  [[-0.37637758 -0.0924276  -0.09875585]
 [ 0.09159578 -0.00603162 -0.4754757 ]
 [-0.4743319   0.24555962 -0.1844385 ]] 

(5, 5)
(3, 3)
(1,) 

Y(man):  [[-0.37637761 -0.09242761 -0.09875586]
 [ 0.09159578 -0.00603163 -0.4754757 ]
 [-0.47433183  0.24555962 -0.1844385 ]]


C:\Users\hjeong\AppData\Local\Temp\ipykernel_16400\1543382660.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_man[i, j] = z


Correlation witn n-channel

In [30]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))
conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
print("y shape: ", y.shape)
print("squeezed y shape: ", y.numpy().squeeze().shape, "\n")

print("Y(tf): ", y.numpy().squeeze(), "\n")

W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)
print(B.shape, "\n")

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1)) # 우선 빈 공간 만들기

for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
        window = images[h:h+k_size, w:w+k_size, :]
        z = np.sum(window * W) + B
        y_man[h, w] = z

print("Y(man): ", y_man)

y shape:  (1, 3, 3, 1)
squeezed y shape:  (3, 3) 

Y(tf):  [[-0.54568946 -1.0295973   0.05161537]
 [ 0.05732201 -0.30262452 -0.6716409 ]
 [-0.70836383  0.08644051  0.10310345]] 

(5, 5, 3)
(3, 3, 3)
(1,) 

Y(man):  [[-0.54568946 -1.02959728  0.05161544]
 [ 0.05732194 -0.30262452 -0.67164081]
 [-0.70836383  0.08644054  0.10310342]]


C:\Users\hjeong\AppData\Local\Temp\ipykernel_16400\2816039438.py:34: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_man[i, j] = z


### Conv Layer with Filters
Shapes with Filters

In [36]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)
W, B = conv.get_weights()

print("input image: ", images.shape)
print("W: ", W.shape, "/ B: ", B.shape)
print("Output image: ", Y.shape, "\n")


input image:  (32, 28, 28, 3)
W:  (3, 3, 3, 5) / B:  (5,)
Output image:  (32, 26, 26, 5) 



Computations with Filters

In [46]:
import numpy as np

images = np.random.randint(low=0, high=10, size=(2, 3, 4))
print(images.shape) # (H, W, C)

# 채널별 출력
for c in range(4):
    print(images[:, :, c])
print()

## 

images = np.transpose(images, (2, 0, 1)) 
print(images.shape) # (C, H, W)

# 채널별 출력
for c in range(4):
    print(images[c, :, :])    

(2, 3, 4)
[[2 0 8]
 [2 6 8]]
[[7 5 3]
 [4 3 9]]
[[4 9 6]
 [7 0 6]]
[[9 6 4]
 [4 8 1]]

(4, 2, 3)
[[2 0 8]
 [2 6 8]]
[[7 5 3]
 [4 3 9]]
[[4 9 6]
 [7 0 6]]
[[9 6 4]
 [4 8 1]]


In [69]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 4
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

### forward propagation (tf)
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)
# print(Y.shape)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(tf): ", Y.shape, "\n", Y)

### forward propagation (manual)
W, B = conv.get_weights()
images = images.numpy().squeeze()

# print(W.shape, B.shape)
# print(images.shape)

Y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter))

for c in range(n_filter):
    c_W = W[:, :, :, c]
    c_B = B[c]
    # print(c_W.shape)
    
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[h:h+k_size, w:w+k_size, :]
            # print(window.shape)
            Y_man[h, w, c] = np.sum(window * c_W) + c_B

Y_man = np.transpose(Y_man, (2, 0, 1))
print("Y(man): ", Y_man.shape, "\n", Y_man)

Y(tf):  (4, 2, 2) 
 [[[-0.3570928   0.34775928]
  [ 0.1495131   0.04881763]]

 [[-0.6019267  -0.095783  ]
  [-0.34438187 -0.13894887]]

 [[ 0.76280797  0.6621494 ]
  [ 0.7922844   1.0797873 ]]

 [[ 0.02123606  0.03763804]
  [-0.19084677 -0.49260855]]]
Y(man):  (4, 2, 2) 
 [[[-0.35709277  0.34775931]
  [ 0.14951313  0.04881769]]

 [[-0.60192674 -0.09578294]
  [-0.34438181 -0.13894889]]

 [[ 0.76280797  0.66214943]
  [ 0.79228449  1.07978737]]

 [[ 0.02123618  0.03763799]
  [-0.1908468  -0.49260858]]]


Conv Layers with Activation Functions

In [72]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 4
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

### forward propagation (tf)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation='sigmoid')
Y = conv(images)
# print(Y.shape)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(tf): ", Y.shape, "\n", Y)

### forward propagation (manual)
W, B = conv.get_weights()
images = images.numpy().squeeze()

# print(W.shape, B.shape)
# print(images.shape)

Y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter))

for c in range(n_filter):
    c_W = W[:, :, :, c]
    c_B = B[c]
    # print(c_W.shape)
    
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[h:h+k_size, w:w+k_size, :]
            # print(window.shape)
            conv = np.sum(window * c_W) + c_B
            Y_man[h, w, c] = 1 / (1 + np.exp(-conv))

Y_man = np.transpose(Y_man, (2, 0, 1))
print("Y(man): ", Y_man.shape, "\n", Y_man)

Y(tf):  (4, 2, 2) 
 [[[0.4155384  0.4670282 ]
  [0.48730835 0.39814928]]

 [[0.670283   0.7058181 ]
  [0.6645797  0.71991986]]

 [[0.40087608 0.41955355]
  [0.44170198 0.3908996 ]]

 [[0.5609696  0.5862361 ]
  [0.59426475 0.7043673 ]]]
Y(man):  (4, 2, 2) 
 [[[0.41553838 0.46702816]
  [0.48730839 0.39814926]]

 [[0.67028299 0.70581818]
  [0.66457967 0.71991984]]

 [[0.40087605 0.41955354]
  [0.44170201 0.39089963]]

 [[0.56096961 0.58623618]
  [0.59426473 0.70436723]]]


### Models with Conv Layers
Models with Sequential Method

In [83]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

model = Sequential()
model.add(Conv2D(filters=n_neurons[0], kernel_size = 3, activation='relu'))
model.add(Conv2D(filters=n_neurons[1], kernel_size = 3, activation='relu'))
model.add(Conv2D(filters=n_neurons[2], kernel_size = 3, activation='relu'))

X = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(X)

# print("X: ", X.shape)
# print("predictions: ", predictions.shape)

for layer in model.layers:
    # print(layer)
    W, B = layer.get_weights()
    print(W.shape, B.shape)
    
print("=====")

trainable_variables = model.trainable_variables
print(len(trainable_variables))
for train_var in trainable_variables:
    print(train_var.shape)

(3, 3, 3, 10) (10,)
(3, 3, 10, 20) (20,)
(3, 3, 20, 30) (30,)
=====
6
(3, 3, 3, 10)
(10,)
(3, 3, 10, 20)
(20,)
(3, 3, 20, 30)
(30,)


In [87]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons
        
        self.conv_layers = []
        
        for n_neuron in n_neurons:
            self.conv_layers.append(Conv2D(filters=n_neuron, kernel_size = 3, activation='relu'))
    
    def call(self, x):
        print("X: ", x.shape)
        
        print("\n===== Conv Layers =====")
        for conv_layer in self.conv_layers:
            x = conv_layer(x)
            W, B = conv_layer.get_weights()
            print("W: ", W.shape, ", B: ", B.shape)
            print("X: ", X.shape, "\n")
        return x

model = TestModel()

X = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(X)

X:  (32, 28, 28, 3)

===== Conv Layers =====
W:  (3, 3, 3, 10) , B:  (10,)
X:  (32, 28, 28, 3) 

W:  (3, 3, 10, 20) , B:  (20,)
X:  (32, 28, 28, 3) 

W:  (3, 3, 20, 30) , B:  (30,)
X:  (32, 28, 28, 3) 

