### 1D Max/Avg Pooling
Max Pooling

In [16]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_avg = MaxPooling1D(pool_size=f, strides=1)
pooled_avg = pool_avg(x)

print("x: ", x.shape, x.numpy().flatten())

print("====")

print("pooled_max(tf): ", pooled_avg.shape, pooled_avg.numpy().flatten())

print("====")

x = x.numpy().flatten()
pooled_avg_man = np.zeros(shape=(L-f+1, )) # 빈 공간 마련
for i in range(L-f+1):
    window = x[i:i+f]
    pooled_avg_man[i] = np.max(window)
print("pooled_max(man): ", pooled_avg_man.shape, pooled_avg_man)


x:  (1, 10, 1) [ 2.8920233   0.09533081 -1.1821508  -0.017394    0.02153041 -0.16575794
  0.17567821  0.41768765 -1.235992   -0.7133007 ]
====
pooled_max(tf):  (1, 9, 1) [ 2.8920233   0.09533081 -0.017394    0.02153041  0.02153041  0.17567821
  0.41768765  0.41768765 -0.7133007 ]
====
pooled_max(man):  (9,) [ 2.89202332  0.09533081 -0.017394    0.02153041  0.02153041  0.17567821
  0.41768765  0.41768765 -0.7133007 ]


Average Pooling

In [17]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size=f, strides=1)
pooled_avg = pool_avg(x)

print("x: ", x.shape, x.numpy().flatten())

print("====")

print("pooled_avg(tf): ", pooled_avg.shape, pooled_avg.numpy().flatten())

print("====")

x = x.numpy().flatten()
pooled_avg_man = np.zeros(shape=(L-f+1, )) # 빈 공간 마련
for i in range(L-f+1):
    window = x[i:i+f]
    pooled_avg_man[i] = np.mean(window)
print("pooled_avg(man): ", pooled_avg_man.shape, pooled_avg_man)


x:  (1, 10, 1) [-0.25895742 -0.62685776  0.48678806 -0.9509754   1.7613645  -2.6327667
 -1.4622571  -0.19159655  0.14958392  1.2808422 ]
====
pooled_avg(tf):  (1, 9, 1) [-0.44290757 -0.07003485 -0.23209368  0.40519452 -0.43570113 -2.047512
 -0.8269268  -0.02100632  0.71521306]
====
pooled_avg(man):  (9,) [-0.44290757 -0.07003485 -0.23209368  0.40519452 -0.43570113 -2.04751205
 -0.82692683 -0.02100632  0.71521306]


### 2D Max/Avg Pooling
Max Pooling

In [10]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = MaxPooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: ", x.shape, x.numpy().squeeze())

print("====")

print("pooled_max(tf): ", pooled_avg.numpy().squeeze().shape, pooled_avg.numpy().squeeze())

print("====")

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H-f+1, n_W-f+1)) # 빈 공간 마련
# print(x.shape, pooled_max_man.shape)

for h in range(n_H-f+1):
    for w in range(n_W-f+1):
        window = x[h:h+f, w:w+f]
        pooled_avg_man[h, w] = np.max(window)

print("pooled_max(man): ", pooled_avg_man.shape, pooled_avg_man)


x:  (1, 5, 5, 1) [[ 0.19611657  1.3494246  -1.2294924  -0.9300468  -0.42458913]
 [-1.1409936   1.1929995   0.13949452 -0.24851546  0.1254662 ]
 [-0.3455199  -0.06685569  1.1535254   0.35475448  0.4694748 ]
 [-1.2560853   0.77089024 -1.2825122  -1.408023    0.8571363 ]
 [ 1.2319617  -1.7328146  -0.6236926   0.48285094 -2.4249656 ]]
====
pooled_max(tf):  (4, 4) [[1.3494246  1.3494246  0.13949452 0.1254662 ]
 [1.1929995  1.1929995  1.1535254  0.4694748 ]
 [0.77089024 1.1535254  1.1535254  0.8571363 ]
 [1.2319617  0.77089024 0.48285094 0.8571363 ]]
====
pooled_max(man):  (4, 4) [[1.3494246  1.3494246  0.13949452 0.1254662 ]
 [1.19299948 1.19299948 1.15352535 0.46947479]
 [0.77089024 1.15352535 1.15352535 0.85713631]
 [1.23196173 0.77089024 0.48285094 0.85713631]]


Average Pooling

In [11]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: ", x.shape, x.numpy().squeeze())

print("====")

print("pooled_avg(tf): ", pooled_avg.numpy().squeeze().shape, pooled_avg.numpy().squeeze())

print("====")

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H-f+1, n_W-f+1)) # 빈 공간 마련
# print(x.shape, pooled_avg_man.shape)

for h in range(n_H-f+1):
    for w in range(n_W-f+1):
        window = x[h:h+f, w:w+f]
        pooled_avg_man[h, w] = np.mean(window)

print("pooled_avg(man): ", pooled_avg_man.shape, pooled_avg_man)

x:  (1, 5, 5, 1) [[ 0.28601244  0.53062636 -0.7037066  -0.92224    -1.2984333 ]
 [-1.1944699   1.4634187   0.9112951   0.41171563 -0.9447627 ]
 [-0.46025935 -0.429038   -0.9459781  -0.06952394 -0.7966157 ]
 [ 0.03956525 -0.34871122 -0.6001071   0.7722165  -0.37823176]
 [-0.6210017  -0.7957154  -0.31128603 -0.5073473  -1.1899222 ]]
====
pooled_avg(tf):  (4, 4) [[ 0.2713969   0.5504084  -0.07573397 -0.6884301 ]
 [-0.15508714  0.24992444  0.07687716 -0.34979668]
 [-0.29961082 -0.5809586  -0.21084817 -0.11803873]
 [-0.43146577 -0.51395494 -0.16163097 -0.3258212 ]]
====
pooled_avg(man):  (4, 4) [[ 0.27139691  0.55040842 -0.07573397 -0.68843007]
 [-0.15508714  0.24992444  0.07687716 -0.34979668]
 [-0.29961082 -0.5809586  -0.21084817 -0.11803873]
 [-0.43146577 -0.51395494 -0.16163097 -0.32582119]]


### 3D Max/Avg Pooing
3D Max Pooling

In [12]:
import tensorflow as tf
import numpy as np
import math

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2, 2

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
# print("x: ", x.shape, np.transpose(x.numpy().squeeze(), (2, 0, 1)))

pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

pooled_max_t = pooled_max.numpy().squeeze()
pooled_max_t = np.transpose(pooled_max_t, (2, 0, 1))
print("pooled_max(tf): ", pooled_max.shape, "\n", pooled_max_t, "\n")

###

x = x.numpy().squeeze()

n_H_ = math.floor((n_H - f)/s + 1)
n_W_ = math.floor((n_W - f)/s + 1)

pooled_max_man = np.zeros(shape=(n_H_, n_W_, n_C)) # initialize
# print(pooled_max_man.shape)

for c in range(n_C):

    h_ = 0
    for h in range(0, n_H-f+1, s):
        w_ = 0
        for w in range(0, n_W-f+1, s):
            window = x[h:h+f, w:w+f, c]
            pooled_max_man[h_, w_, c] = np.max(window)
            w_ += 1
        h_ += 1
print("pooled_max(man): ", pooled_max_man.shape, "\n", np.transpose(pooled_max_man, (2, 0, 1)))

pooled_max(tf):  (1, 2, 2, 3) 
 [[[ 2.535068    1.9994445 ]
  [ 0.61555254  1.4588223 ]]

 [[ 1.3049465   0.45746964]
  [ 1.0579277   0.51538265]]

 [[ 0.28735164 -0.11916433]
  [ 1.2601216   0.16968465]]] 

pooled_max(man):  (2, 2, 3) 
 [[[ 2.53506804  1.99944448]
  [ 0.61555254  1.45882225]]

 [[ 1.30494654  0.45746964]
  [ 1.05792773  0.51538265]]

 [[ 0.28735164 -0.11916433]
  [ 1.26012158  0.16968465]]]
