### Padding
ZeroPadding2D Layer

In [30]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape=(1, 3, 3, 3))
print(np.transpose(images.numpy().squeeze(), (2, 0, 1)))

zero_padding = ZeroPadding2D(padding=1)
y = zero_padding(images)
print(np.transpose(y.numpy().squeeze(), (2, 0, 1)))


[[[-1.2168927  -0.78972983 -0.83574384]
  [-1.6339096   0.910048   -1.8111992 ]
  [-0.71090806  0.2270489   2.3972147 ]]

 [[ 1.256716    1.3430178  -1.2414734 ]
  [-0.07638595  0.92842805 -0.19933304]
  [ 0.0330605  -0.8876815   1.4780048 ]]

 [[-0.19371322  0.7567852  -0.18726139]
  [-1.2246002   0.98030937  0.13346282]
  [-0.20719059 -0.18851155  0.6449295 ]]]
[[[ 0.          0.          0.          0.          0.        ]
  [ 0.         -1.2168927  -0.78972983 -0.83574384  0.        ]
  [ 0.         -1.6339096   0.910048   -1.8111992   0.        ]
  [ 0.         -0.71090806  0.2270489   2.3972147   0.        ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.          0.        ]
  [ 0.          1.256716    1.3430178  -1.2414734   0.        ]
  [ 0.         -0.07638595  0.92842805 -0.19933304  0.        ]
  [ 0.          0.0330605  -0.8876815   1.4780048   0.        ]
  [ 0.          0.          0.          0.          0.  

Zero Padding with Conv2D Layers

In [31]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
pool = Conv2D(filters=1, kernel_size=3, padding='same') # Conv 에서는 padding = ['same', 'valid'] 를 주로 사용
y = pool(images)

print("image: ", images.shape)
print("y: ", y.shape)


image:  (1, 28, 28, 3)
y:  (1, 28, 28, 1)


### Strides
Strides in Conv2D Layers

In [32]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D


images = tf.random.normal(shape=(1, 28, 28, 3))
pool = Conv2D(filters=1, kernel_size=3, padding='valid', strides=2)
y = pool(images)

print("image: ", images.shape)
print("y: ", y.shape)

image:  (1, 28, 28, 3)
y:  (1, 13, 13, 1)


Strides in Pooling Layers

In [33]:
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D


images = tf.random.normal(shape=(1, 28, 28, 3))
pool = MaxPooling2D(pool_size=3, strides=2)
y = pool(images)

print("image: ", images.shape)
print("y: ", y.shape)

image:  (1, 28, 28, 3)
y:  (1, 13, 13, 3)
